# Generated by Django 3.2.5 on 2021-07-19 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MostFrequentQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'سؤال وجواب',
                'verbose_name_plural': 'اسئلة واجوبة',
            },
        ),
    ]
