# Generated by Django 3.2.5 on 2021-07-19 21:27

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_mostfrequentquestions_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='MostFrequentQuestionsOrderable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_qa', to='about.aboutpage')),
                ('questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.aboutpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
