# Generated by Django 3.2.5 on 2021-07-19 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_mostfrequentquestionsorderable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mostfrequentquestionsorderable',
            name='questions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.mostfrequentquestions'),
        ),
    ]
