# Generated by Django 3.2.4 on 2021-07-25 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_alter_mostfrequentquestionsorderable_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mostfrequentquestionsorderable',
            name='page',
        ),
        migrations.RemoveField(
            model_name='mostfrequentquestionsorderable',
            name='questions',
        ),
    ]
