# Generated by Django 3.2.4 on 2021-07-25 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_homemostfrequentquestionsorderable_homequestions'),
        ('about', '0006_auto_20210725_1533'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MostFrequentQuestions',
        ),
        migrations.DeleteModel(
            name='MostFrequentQuestionsOrderable',
        ),
    ]
