# Generated by Django 3.2.5 on 2021-07-22 12:58

from django.db import migrations, models
import django.db.models.deletion
import wagtail.contrib.routable_page.models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('wagtailimages', '0023_add_choose_permissions'),
        ('eventspage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsListingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('custom_title', models.CharField(help_text='صفحة عرض الاحادث الموجودة', max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='EventsDetailsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('event_title', models.CharField(help_text='العنوان الدورة', max_length=100, null=True)),
                ('event_subtitle', models.TextField(help_text='وصف مصغر عن للدورة', max_length=200, null=True)),
                ('event_price', models.CharField(help_text='سعر الدورة', max_length=10, null=True)),
                ('event_duration', models.DateField()),
                ('event_time', models.CharField(help_text='زمن الدورة مثلا 4مساءا الى ال6 مساءا', max_length=20, null=True)),
                ('event_location', models.CharField(help_text='عنوان الحدث', max_length=100, null=True)),
                ('number_of_places', models.CharField(help_text='عدد الاماكن المتاحة', max_length=10, null=True)),
                ('event_video_id', models.CharField(help_text='الأيدي الخاص بالفيديو التعريفي للحدث على اليوتيوب', max_length=50, null=True)),
                ('event_button_text', models.CharField(default='تواصل معنا الان', max_length=50, null=True)),
                ('content', wagtail.core.fields.RichTextField(help_text='محتوى كامل عن الحدث ومحتواها')),
                ('event_image', models.ForeignKey(help_text='صورة للدورة', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
