# Generated by Django 3.2.5 on 2021-07-23 15:48

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('eventspage', '0002_eventsdetailspage_eventslistingpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventsdetailspage',
            name='event_duration',
        ),
        migrations.AddField(
            model_name='eventsdetailspage',
            name='event_date',
            field=models.DateField(blank=True, help_text='تاريخ الدورة اليوم والشهر والعام', null=True),
        ),
        migrations.AlterField(
            model_name='eventsdetailspage',
            name='content',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='محتوى كامل عن الحدث ومحتواها'),
        ),
        migrations.AlterField(
            model_name='eventsdetailspage',
            name='event_location',
            field=models.CharField(blank=True, help_text='مكان الحدث', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='eventsdetailspage',
            name='event_price',
            field=models.CharField(blank=True, help_text='سعر الدورة', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='eventsdetailspage',
            name='event_subtitle',
            field=models.TextField(default='حدث المركز', help_text='وصف مصغر عن للدورة', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='eventsdetailspage',
            name='event_time',
            field=models.CharField(blank=True, help_text='زمن الدورة مثلا 4مساءا الى ال6 مساءا', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='eventsdetailspage',
            name='event_title',
            field=models.CharField(default='حدث المركز', help_text='العنوان الدورة', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='eventsdetailspage',
            name='event_video_id',
            field=models.CharField(blank=True, help_text='الأيدي الخاص بالفيديو التعريفي للحدث على اليوتيوب', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='eventsdetailspage',
            name='number_of_places',
            field=models.CharField(blank=True, help_text='عدد الاماكن المتاحة', max_length=10, null=True),
        ),
    ]
