# Generated by Django 3.2.5 on 2021-07-23 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailsearchpromotions', '0002_capitalizeverbose'),
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('eventspage', '0003_auto_20210723_1648'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventsPage',
        ),
    ]
