# Generated by Django 3.2.5 on 2021-07-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventspage', '0004_delete_eventspage'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsdetailspage',
            name='event_wilaya',
            field=models.CharField(blank=True, help_text='ولاية الحدث', max_length=100, null=True),
        ),
    ]
