# Generated by Django 3.2.4 on 2021-07-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventspage', '0005_eventsdetailspage_event_wilaya'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsdetailspage',
            name='event_subtitle',
            field=models.TextField(default='حدث المركز', help_text='وصف مصغر عن للدورة', max_length=300, null=True),
        ),
    ]
